/**
 * lib/usage.ts
 * Monthly usage tracking and per-site regeneration limits.
 * All reads/writes go through Upstash Redis (kv).
 */

import { kv } from "@/lib/kv";

// ── Plan limits ───────────────────────────────────────────────────────────────
export const PLAN_LIMITS = {
  starter: { runsPerMonth: 20,       sitesTotal: 1,        maxRegenerationsPerSite: 3 },
  growth:  { runsPerMonth: 150,      sitesTotal: 3,        maxRegenerationsPerSite: 5 },
  pro:     { runsPerMonth: Infinity, sitesTotal: 25,        maxRegenerationsPerSite: 5 },
} as const;

export type PlanKey = keyof typeof PLAN_LIMITS;

// ── Key helpers ───────────────────────────────────────────────────────────────
function monthlyKey(email: string): string {
  const now  = new Date();
  const yyyy = now.getUTCFullYear();
  const mm   = String(now.getUTCMonth() + 1).padStart(2, "0");
  return `usage:${email}:${yyyy}:${mm}`;
}

function regenKey(email: string, siteId: string): string {
  return `regen:${email}:${siteId}`;
}

// ── Monthly usage ─────────────────────────────────────────────────────────────
/** Returns how many runs the user has used this calendar month. */
export async function getMonthlyUsage(email: string): Promise<number> {
  try {
    return (await kv.get<number>(monthlyKey(email))) ?? 0;
  } catch (err) {
    console.error("[getMonthlyUsage] Redis error:", err);
    return 0;
  }
}

/**
 * Increments the monthly counter and refreshes its TTL to 35 days.
 * Returns the new count.
 */
export async function incrementUsage(email: string): Promise<number> {
  const key  = monthlyKey(email);
  const prev = (await kv.get<number>(key)) ?? 0;
  const next = prev + 1;
  await kv.set(key, next, { ex: 60 * 60 * 24 * 35 }); // expire after ~35 days
  return next;
}

/**
 * Checks the user's monthly usage against their plan limit.
 * If within limit, increments the counter and returns allowed: true.
 * If at/over limit, returns allowed: false WITHOUT incrementing.
 */
export async function checkAndIncrementUsage(
  email: string,
  plan: string,
): Promise<{ allowed: boolean; used: number; limit: number }> {
  const limits  = PLAN_LIMITS[plan as PlanKey] ?? PLAN_LIMITS.starter;
  const limit   = limits.runsPerMonth;
  const current = await getMonthlyUsage(email);

  if (limit !== Infinity && current >= limit) {
    return { allowed: false, used: current, limit };
  }

  const newCount = await incrementUsage(email);
  return {
    allowed: true,
    used:    newCount,
    limit:   limit === Infinity ? Infinity : limit,
  };
}

// ── Per-site regeneration limits ──────────────────────────────────────────────
/** Returns how many times this site has been regenerated by this user. */
export async function getRegenerationCount(
  email:  string,
  siteId: string,
): Promise<number> {
  return (await kv.get<number>(regenKey(email, siteId))) ?? 0;
}

/**
 * Checks the regen counter against the plan's maxRegenerationsPerSite.
 * If within limit, increments and returns allowed: true.
 * If at/over limit, returns allowed: false WITHOUT incrementing.
 */
export async function checkAndIncrementRegen(
  email:  string,
  siteId: string,
  plan:   string,
): Promise<{ allowed: boolean; count: number; max: number }> {
  const limits = PLAN_LIMITS[plan as PlanKey] ?? PLAN_LIMITS.starter;
  const max    = limits.maxRegenerationsPerSite;
  const key    = regenKey(email, siteId);
  const count  = (await kv.get<number>(key)) ?? 0;

  if (count >= max) {
    return { allowed: false, count, max };
  }

  const next = count + 1;
  await kv.set(key, next, { ex: 60 * 60 * 24 * 365 }); // 1-year TTL
  return { allowed: true, count: next, max };
}
